# Site settings
theme: minima
title: "Dr. Mohammed Hamdan's Blog"
baseurl: "/moha" # Subdirectory for GitHub Pages
url: "https://mhhamdan.github.io" # GitHub Pages domain

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter_opts:
    inline_theme: monokai
    block_theme: monokai

# Future-dated posts handling
future: true

# Collections settings
collections:
  posts:
    output: true

# Plugins
plugins:
  - jekyll-feed

# Permalinks configuration
permalink: /:categories/:year/:month/:day/:title/

# Navigation links
nav_links:
  - title: "Home"
    url: "{{ site.baseurl }}/"
  - title: "Education"
    url: "{{ site.baseurl }}/education.html"
  - title: "Skills"
    url: "{{ site.baseurl }}/skills.html"
  - title: "Experience"
    url: "{{ site.baseurl }}/experience.html"
  - title: "Projects"
    url: "{{ site.baseurl }}/projects.html"
  - title: "Publications"
    url: "{{ site.baseurl }}/publications.html"
  - title: "Blog Posts"
    url: "{{ site.baseurl }}/posts/"
  - title: "Long CV"
    url: "{{ site.baseurl }}/cvs/cv_long.html"
  - title: "Academic CV"
    url: "{{ site.baseurl }}/cvs/cv_academic.html"
  - title: "Industry CV"
    url: "{{ site.baseurl }}/cvs/cv_industry.html"
