# Site settings
theme: minima
title: "Dr. Mohammed Hamdan's Blog"
baseurl: "/moha"
url: "https://mhhamdan.github.io"

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter_opts:
    inline_theme: monokai
    block_theme: monokai

# Future-dated posts handling
future: true

# Collections settings
collections:
  posts:
    output: true

# Plugins
plugins:
  - jekyll-feed

# Permalinks configuration
permalink: /:categories/:year/:month/:day/:title/

# Navigation links
nav_links:
  - title: "Home"
    url: "/index.html"
  - title: "Education"
    url: "/education.html"
  - title: "Skills"
    url: "/skills.html"
  - title: "Experience"
    url: "/experience.html"
  - title: "Projects"
    url: "/projects.html"
  - title: "Publications"
    url: "/publications.html"
  - title: "Blog Posts"
    url: "/posts/"
  - title: "Long CV"
    url: "/cvs/cv_long.html"
  - title: "Academic CV"
    url: "/cvs/cv_academic.html"
  - title: "Industry CV"
    url: "/cvs/cv_industry.html"
