theme: minima
title: "Dr. Mohammed Hamdan's Blog"
baseurl: "/moha"  # GitHub Pages subpath
url: "https://mhhhamdan.github.io"


markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter_opts:
    inline_theme: monokai
    block_theme: monokai
future: true
collections:
  posts:
    output: true

plugins:
  - jekyll-feed

permalink: /:categories/:year/:month/:day/:title/

nav_links:
  - title: "Home"
    url: "/index.html"
  - title: "Education"
    url: "/education.html"
  - title: "Skills"
    url: "/skills.html"
  - title: "Experience"
    url: "/experience.html"
  - title: "Projects"
    url: "/projects.html"
  - title: "Publications"
    url: "/publications.html"
  - title: "Long CV"
    url: "/cvs/cv_long.html"
  - title: "Academic CV"
    url: "/cvs/cv_academic.html"
  - title: "Industry CV"
    url: "/cvs/cv_industry.html"
