theme: minima
title: "Dr. Mohammed Hamdan's Blog"
baseurl: "/moha"  # GitHub Pages subpath
url: "https://MHHamdan.github.io"

markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter_opts:
    inline_theme: monokai
    block_theme: monokai
future: true
collections:
  posts:
    output: true

plugins:
  - jekyll-feed

permalink: /:categories/:year/:month/:day/:title/

nav_links:
  - title: "Home"
    url: "/"
  - title: "Long CV"
    url: "/cv_long/"
  - title: "Academic CV"
    url: "/cv_academic/"
  - title: "Industry CV"
    url: "/cv_industry/"
